name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3, 8.4]
        database: [sqlite, mysql, postgres]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.database }} - ${{ matrix.stability }} - ${{ matrix.os }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_mysql, pdo_pgsql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Create SQLite database
        if: matrix.database == 'sqlite'
        run: touch database.sqlite

      - name: Create MySQL test database
        if: matrix.database == 'mysql'
        run: |
          mysql -h 127.0.0.1 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS bob_test;"
          mysql -h 127.0.0.1 -u root -ppassword -e "SHOW DATABASES;"

      - name: Create PostgreSQL test database
        if: matrix.database == 'postgres'
        env:
          PGPASSWORD: password
        run: |
          psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE bob_test;"
          psql -h 127.0.0.1 -U postgres -c "\l"

      - name: Execute tests - SQLite
        if: matrix.database == 'sqlite'
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database.sqlite
        run: |
          vendor/bin/pest --exclude-group=mysql,postgres --coverage --coverage-clover coverage-sqlite.xml

      - name: Execute tests - MySQL
        if: matrix.database == 'mysql'
        env:
          DB_CONNECTION: mysql
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: bob_test
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
        run: |
          vendor/bin/pest --exclude-group=postgres --coverage --coverage-clover coverage-mysql.xml

      - name: Execute tests - PostgreSQL
        if: matrix.database == 'postgres'
        env:
          DB_CONNECTION: pgsql
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: bob_test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        run: |
          vendor/bin/pest --exclude-group=mysql --coverage --coverage-clover coverage-postgres.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage-${{ matrix.database }}.xml
          flags: ${{ matrix.database }}
          name: ${{ matrix.database }}-coverage
          fail_ci_if_error: false